WebApplication4/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication4.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Portal cliente.";
        }
    }
}

WebApplication4/Pages/AdminEditar.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication4.Logica;
using WebApplication4.Controllers;

namespace WebApplication4.Pages {
    public class AdminEditarModel : PageModel {

        //Clientes
        ClienteDataAccessLayer objCliente = new ClienteDataAccessLayer();
        public List<Cliente> cliente { get; set; }

        //Tipos de cuenta
        TipoCuentaDataAccessLayer objTipoCuenta = new TipoCuentaDataAccessLayer();
        public List<TipoCuenta> tipoCuenta { get; set; }

        //Cuentas
        CuentaDataAccessLayer objCuenta = new CuentaDataAccessLayer();
        public List<Cuenta> cuenta { get; set; }

        //Eventos
        EventoDataAccessLayer objEvento = new EventoDataAccessLayer();
        public List<Evento> evento { get; set; }

        //Modelo tipo de cuenta agreegado para enviar a agregar
        [BindProperty]
        public TipoCuenta tipoCuentaAgregado { get; set; }

        public void OnGet() {

            cliente = objCliente.GetAllClientes().ToList();

            tipoCuenta = objTipoCuenta.GetAllTiposCuenta().ToList();

            cuenta = objCuenta.GetAllCuentas().ToList();

            evento = objEvento.GetAllEventos().ToList();

        }

        public ActionResult OnPostAddTipoCuenta() {
            if (!ModelState.IsValid) {
                return Page();
            }
            objTipoCuenta.AddTipoCuenta(tipoCuentaAgregado);
            //Revisar este return
            return new EmptyResult();
        }
    }
}

WebApplication4/Pages/ConsultasAdmin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication4.Pages {
    public class ConsultasAdminModel : PageModel {
        public void OnGet() {

        }
    }
}

WebApplication4/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication4.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Portal admin.";
        }
    }
}

WebApplication4/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication4.Pages
{
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebApplication4/Pages/ImpersonarCliente.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication4.Logica;
using Microsoft.AspNetCore.Mvc.TagHelpers;

namespace WebApplication4.Pages {
    public class ImpersonarClienteModel : PageModel {


        ClienteDataAccessLayer objCliente = new ClienteDataAccessLayer();

        //Objetos del SP de datos actuales
        public List<Object> listaCuentas { set; get; }
        public Cuenta cuenta { set; get; }
        public List<Movimiento> listaMovimientos { set; get; }

        [BindProperty]
        public Cliente cliente { get; set; }

        //Objetos del SP de estados de cuenta recientes
        public List<EstadoCuenta> listaEstadosCuenta { get; set; }

        public void OnGet() {
            cuenta = new Cuenta();
            listaMovimientos = new List<Movimiento>();

            listaEstadosCuenta = new List<EstadoCuenta>();

        }

        //Se usa el input con name identificacion para hacer el SP y cambiar datos
        public IActionResult OnPost(int identificacion) {
            //Si el id del cliente que se asigna es inválido, refresca la página sin nada nuevo
            if (!ModelState.IsValid) {
                return Page();
            }

            //Corre el SP de datos del cliente
            listaCuentas = objCliente.GetInfoCliente(identificacion);
            //Asigna los objetos
            cuenta = (Cuenta)listaCuentas[0];
            listaMovimientos = (List<Movimiento>)listaCuentas[1];

            //Corre el SP de estados de cuenta y los asigna
            listaEstadosCuenta = objCliente.GetEstadosCuentaRecientes(identificacion).ToList();

            return Page(); //si retorna 0 significa que todo corrió bien
        }
    }
}

WebApplication4/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication4.Logica;
using WebApplication4.Controllers;
using Microsoft.AspNetCore.Server;

namespace WebApplication4.Pages {
    public class IndexModel : PageModel {

        AdministradorDataAccessLayer objAdmin = new AdministradorDataAccessLayer();
        AccountController controlador = new AccountController();

        [BindProperty]
        public Usuario usuario { set; get; }

        public void OnGet() {
            usuario = new Usuario();
            controlador.Logout();

        }

        public IActionResult OnPostAdmin(string username, string pass) {
            if (!ModelState.IsValid) {
                return Page();
            }
            return new EmptyResult();
        }

        public IActionResult OnPostCliente(string username, string pass) {
            if (!ModelState.IsValid) {
                return Page();
            }

            bool resultLogin = objAdmin.VerificarCredencialesAdmin(username, pass);

            return new EmptyResult();
        }

        //public void GetIp(out string ip) {
        //    ip = Request.ServerVariables["REMOTE_ADDR"];
        //}
    }
}

WebApplication4/Pages/InfoCliente.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication4.Pages {
    public class InfoClienteModel : PageModel {
        public string Message { get; set; }

        public void OnGet() {
            Message = "Info Cliente.";
        }
    }
}

WebApplication4/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication4.Pages {
    public class PrivacyModel : PageModel {
        public string Message { get; set; }

        public void OnGet() {
            Message = "Estados de cuenta recientes";
        }
    }
}

WebApplication4/Pages/About.cshtml
@page
@model WebApplication4.Pages.AboutModel
@{
    ViewData["Title"] = "Portal cliente";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

@*Navegación*@
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-page="/Index">Inicio sesión</a></li>
        <li class="breadcrumb-item active" aria-current="page">Portal cliente</li>
    </ol>
</nav>

<h2>@ViewData["Title"]</h2>

@*Botones*@
<div class="d-flex justify-content-between">
    <a class="btn btn-primary btn-lg btn-block" asp-page="/Privacy" tabindex="-1" role="button">Estados de cuenta recientes</a>
    <a class="btn btn-primary btn-lg btn-block" asp-page="/InfoCliente" tabindex="-1" role="button">Información actual</a>
</div>



    @*
        IGNORAR POR AHORA
        <nav>
            <div class="nav nav-tabs" id="nav-tab" role="tablist">
                <a class="nav-item nav-link" id="nav-recientes-tab" data-toggle="tab" href="#nav-recientes" role="tab" aria-controls="nav-recientes" aria-selected="true">Estados de cuenta recientes</a>
                <a class="nav-item nav-link" id="nav-info-tab" data-toggle="tab" href="#nav-info" role="tab" aria-controls="nav-info" aria-selected="false">Información cliente</a>
            </div>
        </nav>
        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="nav-recientes" role="tabpanel" aria-labelledby="nav-recientes-tab">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam consequat pretium turpis malesuada ornare. Sed facilisis enim eu vestibulum placerat. Praesent tempus quam eget neque ultricies ullamcorper. Cras nec rutrum arcu, non ornare felis. Maecenas ac tincidunt urna, eu sodales erat. Cras lacus est, finibus vel dapibus eu, porttitor eu leo. Mauris ullamcorper placerat ex, id dapibus ante vulputate at. Sed pellentesque vel lectus ut suscipit. Vivamus faucibus dignissim placerat. Aliquam erat volutpat. Donec vitae ligula eget leo facilisis tempor. Praesent et lobortis est, ut facilisis velit. Vestibulum condimentum auctor scelerisque. Sed tempus ornare orci, nec hendrerit turpis ultricies at.</div>
            <div class="tab-pane fade" id="nav-info" role="tabpanel" aria-labelledby="nav-info-tab">Phasellus a metus in magna pharetra semper sed sit amet velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque cursus enim condimentum justo ornare, quis vulputate est ultrices. Vestibulum vel leo sit amet arcu rhoncus bibendum. Praesent volutpat tincidunt risus. Aenean sit amet fermentum massa, at efficitur dolor. Nulla sed posuere eros. Nam metus ante, lobortis ut lorem vitae, finibus imperdiet nibh.</div>
        </div>*@

WebApplication4/Pages/ConsultasAdmin.cshtml
@page
@model WebApplication4.Pages.ConsultasAdminModel
@{
    ViewData["Title"] = "Otras consultas";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

@*Navegador*@
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-page="/Index">Inicio sesión</a></li>
        <li class="breadcrumb-item"><a asp-page="/Contact">Portal admin</a></li>
        <li class="breadcrumb-item active" aria-current="page">Otras consultas</li>
    </ol>
</nav>

<h2>@ViewData["Title"]</h2>

@*Acordeon para las consultas*@
<div class="accordion" id="accordionConsultas">
    @*Movimentos*@
    <div class="card">
        <div class="card-header" id="headingMovimientos">
            <h5 class="mb-0">
                <button class="btn btn-primary btn-lg btn-block collapsed" type="button" data-toggle="collapse" data-target="#collapseMovimientos" aria-expanded="false" aria-controls="collapseMovimientos">
                    Movimientos por mes
                </button>
            </h5>
        </div>

        <div id="collapseMovimientos" class="collapse" aria-labelledby="headingMovimientos" data-parent="#accordionConsultas">
            <div class="card-body">
                <form>
                    <p>
                        Rango:
                        <div class="input-group">
                            <input id="mesInicioMovimientos" type="date" placeholder="mes de inicio" />
                            <input id="mesFinMovimientos" type="date" placeholder="mes final" />
                            <input id="btnBuscarMovimientos" class="btn btn-success btn-outline" type="submit" value="Buscar">
                        </div>
                    </p>
                </form>
                
                

                @*Tabla de informacion de movimientos*@
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Código</th>
                            <th scope="col">Saldo promedio</th>
                            <th scope="col">Saldo mínimo</th>
                            <th scope="col">Cant. movimientos</th>
                            <th scope="col">Promedio movimientos</th>
                            <th scope="col">Cant. multas</th>
                            <th scope="col">Suma multas</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">128</th>
                            <td>$4000</td>
                            <td>$20</td>
                            <td>800</td>
                            <td>12.5</td>
                            <td>3</td>
                            <td>$30</td>
                        </tr>
                        <tr>
                            <th scope="row">215</th>
                            <td>$3800</td>
                            <td>$18</td>
                            <td>787</td>
                            <td>15.6</td>
                            <td>4</td>
                            <td>$35</td>
                        </tr>
                        <tr>
                            <th scope="row">223</th>
                            <td>$3550</td>
                            <td>$18</td>
                            <td>678</td>
                            <td>12.2</td>
                            <td>6</td>
                            <td>$60</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    @*Cuentas con mayor volumen*@
    <div class="card">
        <div class="card-header" id="headingVolumen">
            <h5 class="mb-0">
                <button class="btn btn-primary btn-lg btn-block collapsed" type="button" data-toggle="collapse" data-target="#collapseVolumen" aria-expanded="false" aria-controls="collapseVolumen">
                    Cuentas con mayor volumen
                </button>
            </h5>
        </div>

        <div id="collapseVolumen" class="collapse" aria-labelledby="headingVolumen" data-parent="#accordionConsultas">
            <div class="card-body">
                <form>
                    <p>
                        Rango:
                        <div class="input-group">
                            <input id="mesInicioVolumen" type="date" placeholder="mes de inicio" />
                            <input id="mesFinVolumen" type="date" placeholder="mes final" />
                            <input id="btnBuscarVolumen" class="btn btn-success btn-outline" type="submit" value="Buscar">
                        </div>
                    </p>
                </form>

                @*Tabla de clientes con mayor volumen*@
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Id Cliente</th>
                            <th scope="col">Suma créditos</th>
                            <th scope="col">Suma débitos</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">128</th>
                            <td>$4000</td>
                            <td>$3500</td>
                        </tr>
                        <tr>
                            <th scope="row">215</th>
                            <td>$3800</td>
                            <td>$1850</td>
                        </tr>
                        <tr>
                            <th scope="row">223</th>
                            <td>$3550</td>
                            <td>$2200</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

    </div>

</div>

WebApplication4/Pages/Contact.cshtml
@page
@model WebApplication4.Pages.ContactModel
@{
    ViewData["Title"] = "Portal admin";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-page="/Index">Inicio sesión</a></li>
        <li class="breadcrumb-item active" aria-current="page">Portal admin</li>
    </ol>
</nav>

<h2>@ViewData["Title"]</h2>

@*Botones opciones de menu admin*@
<div class="d-flex justify-content-between">
    <a class="btn btn-primary btn-lg btn-block" asp-page="/AdminEditar" tabindex="-1" role="button">Editar</a>
    <a class="btn btn-primary btn-lg btn-block" asp-page="/ImpersonarCliente" tabindex="-1" role="button">Impersonar cliente</a>
    <a class="btn btn-primary btn-lg btn-block" asp-page="/ConsultasAdmin" tabindex="-1" role="button">Otras consultas</a>
</div>

WebApplication4/Pages/ImpersonarCliente.cshtml
@page
@model WebApplication4.Pages.ImpersonarClienteModel
@{
    ViewData["Title"] = "Impersonar Cliente";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

@*Navegación*@
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-page="/Index">Inicio sesión</a></li>
        <li class="breadcrumb-item"><a asp-page="/Contact">Portal admin</a></li>
        <li class="breadcrumb-item active" aria-current="page">Impersonar cliente</li>
    </ol>
</nav>

<h2>@ViewData["Title"]</h2>

@*Búsqueda cliente por identificación*@
<form class="form-inline" method="post">
    <div class="form-group">
        <input asp-for="cliente.Id" class="form-control" type="search" placeholder="identificación cliente" name="identificacion" aria-label="Search" />
        <span asp-validation-for="cliente.Id" class="text-danger"></span>
        <button class="btn btn-success btn-outline" type="submit">Buscar</button>
    </div>
</form>

@*Acordeon impersonar cliente*@
<div class="accordion" id="accordionImpersonar">
    @*Estados de cuenta recientes*@
    <div class="card">
        <div class="card-header" id="headingEstadosRecientes">
            <h5 class="mb-0">
                <button class="btn btn-primary btn-lg btn-block collapsed" type="button" data-toggle="collapse" data-target="#collapseEstadosRecientes" aria-expanded="false" aria-controls="collapseEstadosRecientes">
                    Estados de cuenta recientes
                </button>
            </h5>
        </div>

        <div id="collapseEstadosRecientes" class="collapse" aria-labelledby="headingEstadosRecientes" data-parent="#accordionImpersonar">
            <div class="card-body">
                @*Tabla info estados recientes AUN SIN INFO VERDADERA*@
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th scope="col">Id Cuenta</th>
                            <th scope="col">Fecha corte</th>
                            <th scope="col">Saldo inicial</th>
                            <th scope="col">Saldo final</th>
                            <th scope="col">Cant Op Manual</th>
                            <th scope="col">Cant Op ATM</th>
                            <th scope="col">Saldo mínimo</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.listaEstadosCuenta){
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.IdCuenta)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FechaCorte)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SaldoInicial)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SaldoFinal)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CantOpMaxManual)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CantOpMaxATM)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.SaldoMinimo)
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    @*Información actual*@
    <div class="card">
        <div class="card-header" id="headingInfoActual">
            <h5 class="mb-0">
                <button class="btn btn-primary btn-lg btn-block collapsed" type="button" data-toggle="collapse" data-target="#collapseInfoActual" aria-expanded="false" aria-controls="collapseInfoActual">
                    Información actual del cliente
                </button>
            </h5>
        </div>
        <div id="collapseInfoActual" class="collapse" aria-labelledby="headingInfoActual" data-parent="#accordionImpersonar">
            <div class="card-body">
                
                @*Acordeon opciones para informacion actual*@
                <div id="accordionOpcionesInfoActual">
                    
                    @*Opcion información cliente*@
                    <div class="card">
                        <div class="card-header" id="headingInfoCliente">
                            <h5 class="mb-0">
                                <button class="btn btn-link" data-toggle="collapse" data-target="#collapseInfoCliente" aria-expanded="true" aria-controls="collapseInfoCliente">
                                    Información cliente
                                </button>
                            </h5>
                        </div>
                        
                        <div id="collapseInfoCliente" class="collapse" aria-labelledby="headingInfoCliente" data-parent="#accordionOpcionesInfoActual">
                            <div class="card-body">
                                @*Lista con la información del cliente*@
                                <div class="list-group">
                                    <a class="list-group-item list-group-item-action active">Datos</a>
                                    <a class="list-group-item list-group-item-action">
                                        Saldo actual:
                                        <p class="text-right">@Html.DisplayFor(modelItem => Model.cuenta.Saldo)</p>
                                    </a>
                                    <a class="list-group-item list-group-item-action">
                                        Intereses acumulados:
                                        <p class="text-right">@Html.DisplayFor(modelItem => Model.cuenta.InteresesAcumulados)</p>
                                    </a>
                                    <a class="list-group-item list-group-item-action">
                                        Fecha creación:
                                        <p class="text-right">@Html.DisplayFor(modelItem => Model.cuenta.FechaCreacion)</p>
                                    </a>

                                </div>
                            </div>
                        </div>
                    </div>

                    @*Opcion movimientos actuales*@
                    <div class="card">
                        <div class="card-header" id="headingMovimientosCliente">
                            <h5 class="mb-0">
                                <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseMovimientosCliente" aria-expanded="false" aria-controls="collapseMovimientosCliente">
                                    Movimientos cliente
                                </button>
                            </h5>
                        </div>
                        <div id="collapseMovimientosCliente" class="collapse" aria-labelledby="headingMovimientosCliente" data-parent="#accordionOpcionesInfoActual">
                            <div class="card-body">
                                @*Tabla info movimientos*@
                                <table id="tablaMovimientosCliente" class="table table-striped">
                                    <thead>
                                        <tr>
                                            <th scope="col">Id Tipo Movimiento</th>
                                            <th scope="col">Fecha</th>
                                            <th scope="col">Monto</th>
                                            <th scope="col">Descripción</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.listaMovimientos) {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.IdTipoMovimiento)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Fecha)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Monto)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Descripcion)
                                            </td>
                                        </tr>
                                        }
                                            
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

</div>

WebApplication4/Pages/Index.cshtml
@page
@model WebApplication4.Pages.IndexModel
@{


    ViewData["Title"] = "Inicio de sesión";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

@*Navegación*@
<nav aria-label="breadcrumb" m-3>
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Inicio sesión</li>
    </ol>
</nav>

@*Inicio sesión*@
<div class="login">
    <div class="form">
        <form class="login-form">
            <input type="text" placeholder="identificación" asp-for="usuario.Nombre" name="username" required />
            <input type="password" placeholder="clave" asp-for="usuario.Clave" name="pass" required />
            <button id="btnClientes" asp-page-handler="Cliente" asp-page="/About">Cliente</button>
            <button id="btnAdmin" asp-page-handler="Admin" asp-page="/Contact">Admin</button>

        </form>
    </div>
    @*<p class="text-center">@Html.DisplayFor(modelItem => )</p>*@
</div>


@*<script>
    document.getElementById("myBtn").addEventListener("click", function() *@

WebApplication4/Pages/InfoCliente.cshtml
@page
@model WebApplication4.Pages.InfoClienteModel
@using WebApplication4.Logica;
    @{


        ViewData["Title"] = "Información actual cliente";
        Layout = "~/Pages/Shared/_Layout.cshtml";

        //Variables datos del cliente
        var saldoActual = 520.35;
        var intereses = 20.50;
        var fechaCreacion = "20/2/2018";

        //Movimientos del cliente
        string[] movimiento1 = { "Compras", "3/9/2018", "-$500", "Compra tienda en línea" };
        string[] movimiento2 = { "Compras", "3/9/2018", "-$200", "Compra restaurante comida peruana" };
        string[] movimiento3 = { "Depósito manual", "5/9/2018", "+$100", "Depósito manual" };
    }

    @*Navegador*@
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a asp-page="/Index">Inicio sesión</a></li>
            <li class="breadcrumb-item"><a asp-page="/About">Portal cliente</a></li>
            <li class="breadcrumb-item active" aria-current="page">Información actual</li>
        </ol>
    </nav>

    <h2>@ViewData["Title"]</h2>

    @*Datos cliente*@
    <div class="list-group">
        <a class="list-group-item list-group-item-action active">Datos</a>
        <a class="list-group-item list-group-item-action">
            Saldo actual:
            <p class="text-right">$@saldoActual</p>
        </a>
        <a class="list-group-item list-group-item-action">
            Intereses acumulados:
            <p class="text-right">$@intereses</p>
        </a>
        <a class="list-group-item list-group-item-action">
            Fecha creación:
            <p class="text-right">@fechaCreacion</p>
        </a>

    </div>

    <div class="accordion" id="accordionMovimientos">
        @*Movimientos*@
        <div class="card">
            <div class="card-header" id="headingMovimientos">
                <h5 class="mb-0">
                    <button class="btn btn-primary btn-lg btn-block collapsed" type="button" data-toggle="collapse" data-target="#collapseMovimientos" aria-expanded="false" aria-controls="collapseMovimientos">
                        Movimientos
                    </button>
                </h5>
            </div>

            <div id="collapseMovimientos" class="collapse" aria-labelledby="headingMovimientos" data-parent="#accordionMovimientos">
                <div class="card-body">
                    @*Tabla info movimientos*@
                    <table id="tablaMovimientosCliente" class="table table-striped">
                        <thead>
                            <tr>
                                <th scope="col">Tipo Movimiento</th>
                                <th scope="col">Fecha</th>
                                <th scope="col">Monto</th>
                                <th scope="col">Descripción</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                @foreach (var dato in movimiento1)
                                {
                                    <td>@dato</td>
                                }
                            </tr>
                            <tr>
                                @foreach (var dato in movimiento2)
                                {
                                    <td>@dato</td>
                                }
                            </tr>
                            <tr>
                                @foreach (var dato in movimiento3)
                                {
                                    <td>@dato</td>
                                }
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>